-- vim.api.nvim_create_autocmd({ 'FileType' }, {
--     pattern = { 'coffee' },
--     callback = function()
--         vim.bo.foldmethod = 'indent'
--     end,
-- })

-- vim.api.nvim_create_autocmd({ 'FileType' }, {
--     pattern = { 'vim' },
--     callback = function()
--         vim.bo.foldmethod = 'marker'
--     end,
-- })
